### ISSUE TITLE
chm pages bad looking

### ISSUE THREAD

**Issue by inuxor** [gyunaev/kchmviewer#18]
os : Manjaro unstable 
kchmviewer : 8.0

the Manjaro repo version can not open any chm file  , same as in a closed issue [https://github.com/gyunaev/kchmviewer/issues/10](https://github.com/gyunaev/kchmviewer/issues/10), so i compiled a copy ( qmake && make)
this one can open chm file, but the pages looks like missing some css. 
in my memory there was a setting item in the 7.x versions, but the 8.0 can not do so.

how to  work around?
thank you.

**Comment by u-235** [comment]
Hi.

I had the same problem with styles and scripts under the following conditions:

- QWebEngine 5.15
- The chm file contains pages with `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`

The easiest way to solve this problem is to use QWebKit instead of QWebEngine. To do this you need to make a patch in the `src/src.pro` file:

```diff
--- a/src/src.pro
+++ b/src/src.pro
@@ -109,7 +109,7 @@ LIBS += -lchm -lzip
 
 greaterThan(QT_MAJOR_VERSION, 4) {
     # Qt 5
-    greaterThan(QT_MINOR_VERSION, 5) {
+    greaterThan(QT_MINOR_VERSION, 17) {
         # Qt 5.6+
 #        error("You use Qt5.6+ - QWebEngine is not yet suitable for kchmviewer and is not supported")
         QT += webengine webenginewidgets
```

**Comment by inuxor** [comment]
thank you @u-235 
the problem is solved ！
